.gitmodules
pysass.cpp
sass.py
sasstests.py
setup.py
tox.ini

Things this does:
- Upgrade to libsass==3.1.0 (#38)
- Use the newer not-deprecated api
- Reimplement `compile_dirname` in python (it was dropped from the not-deprecated api)
- The reimplemented `compile_dirname` function replaces `.scss` with `.css` in the output directory (#36)
This is a prerequisite to implementing #13

Upgrade to libsass==3.1.0.  Resolves #36.  Resolves #38.

---

pysass.cpp
sass.py
sassc.py
sasstests.py

This sets the submodule to `3.2.0-beta.2`.
A few notable differences:
- Backtraces are improved
- `image_path` is gone (libsass no longer supports `image-url` function)
- `sass_make_data_context` takes ownership of the string (so we `strdup`)
- Output always ends in a `\n` now
- Improved sourcemap support
- compressed mode now outputs BOM instead of `@charset`
I think it's probably worth merging this? and then when 3.2 drops we should be able to just upgrade.

Preparation for libsass3.2

---

sasstests.py

More changes with the latest beta!

3.2.0-beta.5

---

pysass.cpp

Minor simplification / cleanup

Simplify OUTPUT_STYLES constant

---

setup.py

Fixes #34
Using OS X dirty hack for FreeBSD
Travis CI does not have a FreeBSD environment, so I guess no regression tests.

Fix problem compiling package under FreeBSD

---

pysass.cpp

The `expanded` output type was misspelled as `expected` in 54d3b9d88909f3784d00b1470d56a0661d7085df. :)

Fix typo in expanded output style

---

sassutils/wsgi.py

This pull request fixes issue #67, and fixes up whitespace handling for errors in CSS.

Update error_status to HTTP status code 200 instead of 500, Update SASS error style

---

sassutils/distutils.py

Correct typographical error in variable name build_sass.description

Correct variable name build_sass.description

---

sass.py

When compiling using `sass.compile(dirname=(source_dir, output_dir))`, `.sass` files where not detected. With this small commit `.sass` files are now found and everything seems to work nicely.

Added rules to discover `.sass` files when compiling directories

---

sass.py

Fixes #72, using `from io import open` for Python 2 support.

Write output file using UTF-8 encoding

---

MANIFEST.in
Makefile
pysass.cpp
sasstests.py
setup.py

sass/libsass has started development again \o/
This brings us up to speed with the latest released beta.  Our tests seem to pass still which is great!  Needed to adjust the build slightly for the breaking reorganization they did in 3.3.  Other than that, the usual srcmap changes are the only other thing

Libsass 3.3 betas

---

pysass.cpp

The new upstream release is here \o/

Upgrade to 3.3.0 (stable)

---

pysass.cpp
sass.py
sasstests.py

Support for string compilation using indented (SASS) string syntax.

---

setup.py

From http://stevedower.id.au/blog/building-for-python-3-5-part-two/

Fix windows wheels.  Resolves #28.  Resolves #49

---

sassc.py

See #98 
I've left the old options in for compatibility, we can remove them in a later version

Allow -t for style like sassc

---

.travis.yml
appveyor.yml
requirements-dev.txt
sasstests.py
setup.py
tox.ini

Use pytest instead of setup.py test

---

sass.py
sasstests.py

Before you'd get sadness like this:
```python
>>> sass.compile(string='a{')
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/asottile/workspace/libsass-python/sass.py", line 648, in compile
raise CompileError(v)
sass.CompileError: b'Error: Invalid CSS after "a{": expected "}", was ""\n        on line 1 of stdin\n>> a{\n   -^\n'
```

Improve the formatting of CompileErrors in py3

---

setup.py

Remove support for unstable

---

sass.py
sassc.py

Oops, meant to include this in the previous branch but it got merged too quickly :D

Expose libsass_version in public api

---

sass.py

Poked around with this in windows and it seems libsass itself does this transformation for us already \o/

Remove json workaround (fixed upstream at some point)

---

.coveragerc
CONTRIBUTING.rst
build_manylinux_wheels.py

Resolves #75
Resolves #150
CC @samuelcolvin
For more on the "manylinux" spec, see the pep: https://www.python.org/dev/peps/pep-0513/
(Personal notes):
- I really don't like the manylinux spec for the way it bundles `.so` files into the wheel (which has security implications) -- but in our case it doesn't actually bundle any of the shared objects as these are the only things linked (yay?):
```
linux-vdso.so.1 =>  (0x00007ffcab9aa000)
libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fbfb695c000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fbfb6653000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fbfb643c000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fbfb621f000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 …
```

Add a script to build manylinux wheels

---

.travis.yml
README.rst
setup.py

Drop python2.6 support

---

sass.py
sassc.py
sasstests.py
sassutils/builder.py

Preserve line endings that libsass hands us

---

setup.py

- Disable debug symbols under msvc to avoid buggy /DEBUG mode
- Remove python2.6 msvc monkeypatch
- Update libsass submodule to 3.3.6
This may fix the problem that prevented us from bumping to 3.3.6, this patch includes that bump

Upgrade libsass to 3.3.6

---

sassutils/wsgi.py

This took me longer than I care to admit to figure out :)
the warnings were point at unrelated lines.  In order to figure out the actual lines you need to write the docstring to a file and run `rst2html.py` against that file (and then ignore the sphinx-specific directive error messages).
The raw string is to fix 2 `\n`s in a code block.  I removed the comments around the css just for readability.  The actual fix was removing an extraneous `:` a few lines up.

Fix warnings when building sphinx docs.  Resolves #179

---

pysass.cpp
sass.py
sasstests.py

Yay new beta!
Upstream has an abi breaking change which translates to a breaking change for us (`SassList` now has an additional required parameter)

Upgrade libsass to 3.5.0.beta1

---

pysass.cpp

I think these were only necessary in python2.5, the PyBytes and PyLong helpers were added in python2.6

Simplify C macros

---

sass.py

Use getfullargspec over deprecated getargspec

---

.gitignore

Git keeps bugging me about a .cache folder.

Ignore pytests's cache folder

---

.travis.yml
pysass.cpp
sass.py
sassc.py
sasstests.py

Resolves #201
There's now an "output_filename_hint" which can be passed to `sass.compile` while in `filename=` mode which helps libsass make the right decisions on relative paths

Correct source map url (relative to sourcemap file)

---

sassc.py

This was deprecated back in October 2016, we can probably remove it now (or at least soon!): https://github.com/dahlia/libsass-python/releases/tag/0.11.2 and release 0.13.0

Remove deprecated --watch

---

pysass.cpp
sass.py
sasstests.py

It looks like upstream won't be ready to release these for a while so I'd like to make some more 3.4 releases while they're still pumping those out.
I thought about using a branched workflow but that really just complicates things for a temporary situation.
I *think* the easiest way forward is to temporarily revert these, and then when we're ready to go to 3.5, revert this merge commit and we're there!

Temporarily revert the 3.5 releases

---

sass.py
sasstests.py

If #208 doesn't get changed upstream, we can solve it here.
I removed the documentation about passing in `str` for `include_paths`, it never worked due to the following:
```python
>>> isinstance('hi', collections.Sequence)
True
>>> os.pathsep.join('hi')
'h:i'
```
I also removed the custom `TypeError` (just allowing `tuple(...)` to raise)

Always include cwd in import paths

---

setup.py

when building packages (e.g. for openSUSE Linux)
(random) filesystem order of input files
influences ordering of functions in the output,
thus without the patch, builds (in disposable VMs) would usually differ.
See https://reproducible-builds.org/ for why this matters.
as an alternative to PR #211

Sort input files

---

setup.py

This PR implements solution for using system-installed libsass library to build the python sass extension.
This will help to get rid of some hacks/downstream-patches in Fedora and other distributions' packaging.

System sass

---

CONTRIBUTING.rst
README.rst
docs/conf.py
docs/index.rst
setup.py
upload_appveyor_builds.py

See #229 
I think this mostly handles the urls that changed -- I think ci things are still at the old url? (I guess we'll find out!).

Update url from dahlia/libsass-python => sass/libsass-python

---

CONTRIBUTING.rst
LICENSE
README.rst
docs/changes.rst
docs/conf.py
docs/frameworks/flask.rst
docs/index.rst
pysass.cpp
sass.py
sassutils/__init__.py
sassutils/builder.py
sassutils/distutils.py
sassutils/wsgi.py
setup.py

This pull request:
- Changes SASS to Sass.
- Changes Libsass to LibSass.
- Fixes some dead or redirecting links.
- Updates websites that now support a secure connection to `https`. This prevents the user from requesting an insecure URL when a secure one exists.

Various documentation improvements

---

setup.py

The docs have some non-ideal output when run with python2.  Here's an example commit which reruns as python3 (demonstrating the differences):
https://github.com/sass/libsass-python/commit/e756ae7a163d3e8409f0722f206be07ec3ab07e9

upload_doc must be run with python 3

---

sass.py
sassutils/builder.py
sassutils/wsgi.py

`collections.X` => `collections.abc.X` so links in docs work better

Use the python3 names in docstrings

---

pysass.cpp
sass.py
sasstests.py

I know the branch name says _beta_, this was the long-running tracking branch of upstream.
Here's the things that changed from our end:
- `SassList` grew a new keyword argument `bracketed=False`.  The default value here is to maintain api parity with previous versions of `libsass-python` (upstream doesn't really specify a default here -- it either _is_ or _isn't_) -- hopefully this makes upgrading more smooth :)
Here's the [upstream release notes](https://github.com/sass/libsass/releases/tag/3.5.0)

Update to 3.5.0 release!

---

pysass.cpp
sass.py
sassc.py
sasstests.py

fix #245, ref https://github.com/sass/libsass/commit/e690924f83bf726cf259fc11846356a69dcbe491

support custom import extension

---

sasstests.py
sassutils/builder.py

Well rested from my vacation, I was planning to look at a fix for #55, as discussed in #215. Then I was pleasantly surprised to find that #258 fixed it while I was away, and that #215 now could be closed :-)
However, I did not find #258 to work at all. The `build_sass` build command invokes `Manifest.build()`, which in turn invokes the `build_directory()` function to compile an entire directory structures of SASS files. #258 only patches and tests the `Manifest.build_one()` method, which is apparently never invoked by `build_sass`.
This PR attempts to remedy that.

Honor strip_extension option when building entire directory structures from distutils

---

sassutils/distutils.py

The `build_sass` command adds the list of compiled css files to the distribution's `data_files` attribute.
However, it does not add entries that are according to distutils' spec. This causes commands like `python setup.py bdist` or `pip install` to crash.
According to the docs, an entry in `data_files` should either be a single string, or a two-tuple of `(dir_name, [list_of_files])`. The existing code instead adds two-tuples of `(dir_name, file_name)` for each file, causing distutils to attempt to iterate over the characters of the `file_name` string and crash when it attempts to copy a non-existent, one-character-named file.
I'm not entirely sure how to write an effective test for this (and there doesn't seem to be an existing one to cover this code path).
An example of a typical …

Fix distutils bdist crash

---

setup.py

Use -lc++ on macos too

---

pysass.cpp
pysassc.py
sass.py
sasstests.py

upstream libsass removed `sass_option_push_import_extension` -- I did my best to maintain compatibility

libsass 3.5.5

---

setup.py

Use -stdlib=libc++ flag for clang

---

sasstests.py
sassutils/builder.py

See https://github.com/sass/libsass-python/issues/55#issuecomment-440318896

Support .sass extension for the wsgi middleware

---

pysass.cpp
pysassc.py
sass.py
sasstests.py
test/h.sass

I had the need to be able to emit source maps using libsass-python that contain `sourcesContent`. When I set out to make a PR to add this functionality I realized that there are quite a few libsass options not exposed through the API, and also that the cli script does not allow setting all of the options that _are_ already exposed. With these PR, the library and cli script are brought into feature parity with other libsass bindings, such as node-sass.
Newly added kwargs include:
- `source_map_contents`: Emits `sourcesContent` property in source map (fixes #268)
- `source_map_embed`: Embeds sourcemap as a data uri in `sourceMappingURL` comment
- `omit_source_map_url`: Omits the source map comment from the css output file
- `source_map_root`: Sets the `sourceRoot` property in a source map …

Add more cli opts and source map config args

---

pysass.cpp
sass.py
sasstests.py

This change adds feature-parity with node-sass importers, where callbacks are passed both the value of the import directive and the path from which the directive was made. This is particularly useful in cases where the importer needs to resolve relative paths.
I wasn't sure about the best way to go about maintaining backwards-compatibility. Here I added a conditional getargspec call in the importer callback wrapper, but I'm open to any other suggestions.

Add support for passing previous file to importer callback

---

sass.py
sasstests.py

This is the follow up PR based on the discussion in #287.
I removed the `functools.wraps` decorator because it doesn't work with `object.__call__` or `functools.partial` (since neither have the `__name__` attribute). But it seemed unnecessary anyway because (as far as I can tell) the wrapped functions aren't exposed to the user.

Allow partials and other non-function callables as importer callbacks

---

.pre-commit-config.yaml
sass.py
sasstests.py
sassutils/builder.py
sassutils/wsgi.py

Committed via https://github.com/asottile/all-repos

Run pre-commit autoupdate

---

sass.py

found via [flake8-2020](https://github.com/asottile/flake8-2020)

Use `not PY2` instead of `PY3` for python4.x compat

---

.pre-commit-config.yaml
README.rst
azure-pipelines.yml
sasstests.py
sassutils/builder.py
sassutils/wsgi.py
setup.py
tox.ini

Committed via https://github.com/asottile/all-repos

Update azure-pipelines template repositories

---

README.rst
docs/changes.rst
docs/index.rst
sass.py
sassutils/wsgi.py

automated with `pre-commit try-repo https://github.com/codespell-project/codespell --all-files`

a few spelling fixes

---

sassutils/builder.py

Whilst working on the [Reproducible Builds effort](https://reproducible-builds.org/) we noticed that libsass-python could not be built reproducibly. This is due to the manpage containing content that is generated by iterating over a Python `frozenset` type, which is non-deterministic.
This was originally filed in Debian as [#971527](https://bugs.debian.org/971527).

Make the build reproducible

---

.github/workflows/main.yml
setup.py

does not apply on latest setuptools

remove msvc hack
